<template lang="pug">
  el-select.SelectIcon(v-model="localValue" placeholder="Select" filterable)
    el-option(:label="$t('SelectIcon.noIcon')", value="no-icon")
    el-option(
      v-for="iconName in icons"
      :key="iconName"
      :label="iconName"
      :value="`el-icon-${iconName}`"
    )
      i.SelectIcon-icon(:class="`el-icon-${iconName}`")
      span {{ iconName }}
</template>

<script>
import { Option, Select } from 'element-ui'

export default {
  name: 'SelectIcon',

  components: {
    [Option.name]: Option,
    [Select.name]: Select,
  },

  props: {
    value: {
      default: '',
      required: true,
      type: String,
    },
  },

  data() {
    return {
      icons: [
        'add-location',
        'aim',
        'alarm-clock',
        'apple',
        'arrow-down',
        'arrow-left',
        'arrow-right',
        'arrow-up',
        'attract',
        'back',
        'bangzhu',
        'bank-card',
        'baseball',
        'basketball',
        'bell',
        'bicycle',
        'bottom',
        'bottom-left',
        'bottom-right',
        'box',
        'brush',
        'burger',
        'c-scale-to-original',
        'camera',
        'camera-solid',
        'caret-bottom',
        'caret-left',
        'caret-right',
        'caret-top',
        'chat-dot-round',
        'chat-dot-square',
        'chat-line-round',
        'chat-line-square',
        'chat-round',
        'chat-square',
        'check',
        'cherry',
        'chicken',
        'circle-check',
        'circle-close',
        'circle-plus',
        'circle-plus-outline',
        'close',
        'close-notification',
        'cloudy',
        'cloudy-and-sunny',
        'coffee',
        'coffee-cup',
        'coin',
        'cold-drink',
        'collection',
        'collection-tag',
        'connection',
        'coordinate',
        'copy-document',
        'cpu',
        'crop',
        'd-arrow-left',
        'd-arrow-right',
        'd-caret',
        'data-analysis',
        'data-board',
        'data-line',
        'date',
        'delete',
        'delete-location',
        'delete-solid',
        'dessert',
        'discount',
        'discover',
        'dish',
        'dish-1',
        'document',
        'document-add',
        'document-checked',
        'document-copy',
        'document-delete',
        'document-remove',
        'download',
        'edit',
        'edit-outline',
        'eleme',
        'error',
        'female',
        'files',
        'film',
        'finished',
        'first-aid-kit',
        'folder',
        'folder-add',
        'folder-checked',
        'folder-delete',
        'folder-opened',
        'folder-remove',
        'food',
        'football',
        'fork-spoon',
        'full-screen',
        'goblet',
        'goblet-full',
        'goblet-square',
        'goblet-square-full',
        'goods',
        'grape',
        'guide',
        'headset',
        'heavy-rain',
        'help',
        'hot-water',
        'house',
        'ice-cream',
        'ice-cream-round</ul>',
        'ice-cream-square',
        'ice-drink',
        'ice-tea',
        'info',
        'key',
        'knife-fork',
        'light-rain',
        'lightning',
        'link',
        'loading',
        'location',
        'location-information',
        'location-outline',
        'lock',
        'lollipop',
        'magic-stick',
        'male',
        'map-location',
        'medal',
        'medal-1',
        'menu',
        'message',
        'message-solid',
        'mic',
        'microphone',
        'milk-tea',
        'minus',
        'mobile',
        'mobile-phone',
        'money',
        'monitor',
        'moon',
        'moon-night',
        'more',
        'more-outline',
        'mouse',
        'news',
        'no-smoking',
        'notebook-1',
        'notebook-2',
        'odometer',
        'office-building',
        'open',
        'orange',
        'paperclip',
        'partly-cloudy',
        'pear',
        'phone',
        'phone-outline',
        'picture',
        'picture-outline',
        'picture-outline-round',
        'pie-chart',
        'place',
        'platform-eleme',
        'plus',
        'position',
        'postcard',
        'potato-strips',
        'present',
        'price-tag',
        'printer',
        'question',
        'rank',
        'reading',
        'receiving',
        'refresh',
        'refresh-left',
        'refresh-right',
        'refrigerator',
        'remove',
        'remove-outline',
        'right',
        's-check',
        's-claim',
        's-comment',
        's-cooperation',
        's-custom',
        's-data',
        's-finance',
        's-flag',
        's-fold',
        's-goods',
        's-grid',
        's-help',
        's-home',
        's-management',
        's-marketing',
        's-open',
        's-operation',
        's-opportunity',
        's-order',
        's-platform',
        's-promotion',
        's-release',
        's-shop',
        's-ticket',
        's-tools',
        's-unfold',
        'school',
        'scissors',
        'search',
        'sell',
        'service',
        'set-up',
        'setting',
        'share',
        'ship',
        'shopping-bag-1',
        'shopping-bag-2',
        'shopping-cart-1',
        'shopping-cart-2',
        'shopping-cart-full',
        'smoking',
        'soccer',
        'sold-out',
        'sort',
        'sort-down',
        'sort-up',
        'star-off',
        'star-on',
        'stopwatch',
        'success',
        'sugar',
        'suitcase',
        'suitcase-1',
        'sunny',
        'sunrise',
        'sunrise-1',
        'sunset',
        'switch-button',
        'table-lamp',
        'tableware',
        'takeaway-box',
        'thumb',
        'tickets',
        'time',
        'timer',
        'toilet-paper',
        'top',
        'top-left',
        'top-right',
        'trophy',
        'trophy-1',
        'truck',
        'turn-off',
        'turn-off-microphone',
        'umbrella',
        'unlock',
        'upload',
        'upload2',
        'user',
        'user-solid',
        'video-camera',
        'video-camera-solid',
        'video-pause',
        'video-play',
        'view',
        'wallet',
        'warning',
        'warning-outline',
        'watch',
        'watch-1',
        'water-cup',
        'watermelon',
        'wind-power',
        'zoom-in',
        'zoom-out',
      ],
    }
  },

  computed: {
    localValue: {
      get() {
        return this.value
      },
      set(value) {
        this.$emit('input', value)
      },
    },
  },
}
</script>

<style lang="stylus">
.SelectIcon
  &-icon
    color teal
    margin-right 10px
</style>
